# Voter participation in 1844 election


Find this notebook on the web at
<a class="quarto-xref" href="https://resampling-stats.github.io/latest-r/exercise_solutions.html#nte-voter_participation_solution">Note <span>A.6</span></a>.

Solution for voter participation exercise.

```{r}
voter_df <- read.csv('data/election_1844.csv')
participation <- voter_df$Participation
spread <- voter_df$Spread
```

```{r}
# Compute correlation.  It's -0.425.
actual_r <- cor(participation, spread)
actual_r
```

```{r}
n_trials <- 10000
results <- numeric(n_trials)

for (i in 1:n_trials) {
    # Shuffle the participation rates.
    shuffled <- sample(participation)
    # Compute re-sampled correlation.
    fake_r <- cor(shuffled, spread)
    # Keep the value in the results.
    results[i] <- fake_r
}

hist(results, breaks=25,
     main='Distribution of shuffled correlations',
     xlab='Correlation with shuffled participation')

# Count the trials when result <= observed.
k <- sum(results <= actual_r)
# Compute the proportion of such trials.
kk <- k / n_trials

message('Proportion of shuffled r <= observed: ', round(kk, 2))
```
